# Generated by Django 5.2.17 on 2026-09-07 09:59

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Номер замовлення')),
                ('full_name', models.CharField(max_length=180, verbose_name='ПІБ')),
                ('phone', models.CharField(max_length=32, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('delivery_method', models.CharField(choices=[('np_branch', 'Нова Пошта — відділення'), ('np_locker', 'Нова Пошта — поштомат'), ('np_courier', 'Нова Пошта — курʼєр'), ('ukrposhta', 'Укрпошта'), ('pickup', 'Самовивіз')], max_length=16, verbose_name='Спосіб доставки')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='Місто')),
                ('warehouse', models.CharField(blank=True, max_length=200, verbose_name='Відділення / адреса')),
                ('payment_method', models.CharField(choices=[('liqpay', 'Оплата карткою (LiqPay)'), ('cod', 'Оплата при отриманні (накладений платіж)'), ('cash_pickup', 'Оплата при самовивозі')], max_length=16, verbose_name='Спосіб оплати')),
                ('payment_status', models.CharField(choices=[('pending', 'Очікує оплати'), ('paid', 'Оплачено'), ('failed', 'Помилка оплати')], default='pending', max_length=16, verbose_name='Статус оплати')),
                ('status', models.CharField(choices=[('new', 'Нове'), ('processing', 'В обробці'), ('shipped', 'Відправлено'), ('done', 'Виконано')], default='new', max_length=16, verbose_name='Статус замовлення')),
                ('comment', models.TextField(blank=True, verbose_name='Коментар до замовлення')),
                ('promo_code', models.CharField(blank=True, max_length=40, verbose_name='Промокод')),
                ('discount_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Сума знижки')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Сума товарів')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='До сплати')),
                ('agreed_to_data_processing', models.BooleanField(default=False, verbose_name='Згода на обробку даних')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Назва товару (на момент купівлі)')),
                ('variant_label', models.CharField(blank=True, max_length=80, verbose_name='Варіант (на момент купівлі)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна за од.')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Кількість')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Замовлення')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='catalog.product', verbose_name='Товар')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='catalog.productvariant', verbose_name='Варіант')),
            ],
            options={
                'verbose_name': 'Позиція замовлення',
                'verbose_name_plural': 'Позиції замовлення',
            },
        ),
    ]
