# Generated by Django 5.2.17 on 2026-09-08 13:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='Код')),
                ('discount_type', models.CharField(choices=[('percent', 'Відсоток'), ('fixed', 'Фіксована сума')], default='percent', max_length=10, verbose_name='Тип знижки')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Розмір знижки')),
                ('min_subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Мін. сума товарів')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Діє до')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоди',
                'ordering': ['code'],
            },
        ),
    ]
