# Generated by Django 5.2.17 on 2026-09-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_promocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='np_city_ref',
            field=models.CharField(blank=True, max_length=64, verbose_name='NP CityRef'),
        ),
        migrations.AddField(
            model_name='order',
            name='np_warehouse_ref',
            field=models.CharField(blank=True, max_length=64, verbose_name='NP WarehouseRef'),
        ),
    ]
