# Generated by Django 5.2.17 on 2026-09-29 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_payment_bank_transfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutNonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Токен оформлення',
                'verbose_name_plural': 'Токени оформлення',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_is_free',
            field=models.BooleanField(default=False, verbose_name='Безкоштовна доставка'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='max_uses',
            field=models.PositiveIntegerField(blank=True, help_text='Порожньо — без ліміту.', null=True, verbose_name='Ліміт використань'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='used_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Використано разів'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Очікує оплати'), ('paid', 'Оплачено'), ('failed', 'Помилка оплати'), ('refunded', 'Повернено')], default='pending', max_length=16, verbose_name='Статус оплати'),
        ),
    ]
