# Generated by Django 5.2.17 on 2026-09-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(blank=True, max_length=120, verbose_name='Надпис над заголовком')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('lead', models.TextField(blank=True, verbose_name='Підпис')),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Зображення')),
                ('cta1_text', models.CharField(default='Дивитись каталог', max_length=60, verbose_name='Текст кнопки 1')),
                ('cta1_url', models.CharField(default='/katalog/', max_length=255, verbose_name='Посилання кнопки 1')),
                ('cta2_text', models.CharField(blank=True, default='До акцій', max_length=60, verbose_name='Текст кнопки 2')),
                ('cta2_url', models.CharField(blank=True, default='/katalog/aktsiyi/', max_length=255, verbose_name='Посилання кнопки 2')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Слайд банера',
                'verbose_name_plural': 'Слайди банера',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HighlightPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('trust', 'Смуга довіри (під хедером)'), ('info', 'Інфо-картки (переваги)')], default='trust', max_length=10, verbose_name='Секція')),
                ('icon', models.CharField(default='leaf', help_text='Ключ іконки: leaf, truck, shield, card, phone, seed', max_length=30, verbose_name='Іконка')),
                ('title', models.CharField(max_length=120, verbose_name='Заголовок')),
                ('text', models.CharField(blank=True, max_length=200, verbose_name='Текст')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Перевага',
                'verbose_name_plural': 'Переваги',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name="Ім'я")),
                ('text', models.TextField(verbose_name='Текст відгуку')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='Оцінка (1–5)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Відгук',
                'verbose_name_plural': 'Відгуки',
                'ordering': ['order', '-id'],
            },
        ),
    ]
