# Generated by Django 5.2.17 on 2026-09-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='city',
            field=models.CharField(blank=True, max_length=80, verbose_name='Місто'),
        ),
        migrations.AlterField(
            model_name='highlightpoint',
            name='icon',
            field=models.CharField(default='leaf', help_text='Ключ іконки: leaf, truck, shield, card, chat, phone, seed', max_length=30, verbose_name='Іконка'),
        ),
    ]
