# Generated by Django 5.2.17 on 2026-09-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutIntroSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Про нас — Інтро',
                'verbose_name_plural': 'Про нас — Інтро',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='AboutPhilosophySettings',
            fields=[
            ],
            options={
                'verbose_name': 'Про нас — Філософія',
                'verbose_name_plural': 'Про нас — Філософія',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='AboutProduceSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Про нас — CTA',
                'verbose_name_plural': 'Про нас — CTA',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='AboutShelvesSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Про нас — Полички',
                'verbose_name_plural': 'Про нас — Полички',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='AboutTimelineSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Про нас — Хронологія',
                'verbose_name_plural': 'Про нас — Хронологія',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='AboutWhySettings',
            fields=[
            ],
            options={
                'verbose_name': 'Про нас — Чому ми',
                'verbose_name_plural': 'Про нас — Чому ми',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='CartPageSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Кошик',
                'verbose_name_plural': 'Кошик',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='CatalogPageSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Каталог — сторінка',
                'verbose_name_plural': 'Каталог — сторінка',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='CertificatesPageSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Сертифікати — сторінка',
                'verbose_name_plural': 'Сертифікати — сторінка',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='CheckoutPageSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Оформлення',
                'verbose_name_plural': 'Оформлення',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='ContactsPageSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Контакти',
                'verbose_name_plural': 'Контакти',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='DeliveryPageSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Доставка і оплата',
                'verbose_name_plural': 'Доставка і оплата',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='Error404Settings',
            fields=[
            ],
            options={
                'verbose_name': 'Сторінка 404',
                'verbose_name_plural': 'Сторінка 404',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='HomeBenefitsSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Головна — Переваги',
                'verbose_name_plural': 'Головна — Переваги',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='HomeCategoriesSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Головна — Категорії',
                'verbose_name_plural': 'Головна — Категорії',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='HomeHeroSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Головна — Hero',
                'verbose_name_plural': 'Головна — Hero',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='HomeHitsSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Головна — Хіти',
                'verbose_name_plural': 'Головна — Хіти',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='HomeNewsSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Головна — Новинки',
                'verbose_name_plural': 'Головна — Новинки',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='HomeReviewsSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Головна — Відгуки',
                'verbose_name_plural': 'Головна — Відгуки',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='HomeSaleSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Головна — Акції',
                'verbose_name_plural': 'Головна — Акції',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='HomeStorySettings',
            fields=[
            ],
            options={
                'verbose_name': 'Головна — Історії',
                'verbose_name_plural': 'Головна — Історії',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='HomeTrustSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Головна — Довіра',
                'verbose_name_plural': 'Головна — Довіра',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='OfferPageSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Оферта',
                'verbose_name_plural': 'Оферта',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='PrivacyPageSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Політика',
                'verbose_name_plural': 'Політика',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='SearchPageSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Пошук',
                'verbose_name_plural': 'Пошук',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='SiteFabSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Кнопка звʼязку',
                'verbose_name_plural': 'Кнопка звʼязку',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='SiteFooterSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Підвал',
                'verbose_name_plural': 'Підвал',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='SiteHeaderSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Шапка',
                'verbose_name_plural': 'Шапка',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='SiteLeadModalSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Модалка заявки',
                'verbose_name_plural': 'Модалка заявки',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='ThankYouPageSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Дякуємо',
                'verbose_name_plural': 'Дякуємо',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='alt_text',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Alt зображення'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address',
            field=models.CharField(blank=True, default='м. Київ, Хрещатик 1', max_length=255, verbose_name='Адреса / точка видачі'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='free_shipping_threshold',
            field=models.PositiveIntegerField(default=1500, verbose_name='Безкоштовна доставка від (₴)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_description',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Meta description (за замовчуванням)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(blank=True, default='+38 (067) 123-45-67', max_length=32, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='phone_raw',
            field=models.CharField(blank=True, default='+380671234567', help_text='Лише цифри та +, для посилання tel:', max_length=32, verbose_name='Телефон для tel:'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='Соняшник', max_length=128, verbose_name='Назва сайту'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='work_hours',
            field=models.CharField(blank=True, default='Пн–Сб 9:00–18:00', max_length=120, verbose_name='Графік роботи'),
        ),
        migrations.AlterField(
            model_name='highlightpoint',
            name='icon',
            field=models.CharField(default='leaf', help_text='Ключ іконки: leaf, truck, shield, card, chat, phone, seed, years', max_length=30, verbose_name='Іконка'),
        ),
        migrations.CreateModel(
            name='SiteBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Головна'), ('site', 'Сайт'), ('about', 'Про нас'), ('delivery', 'Доставка'), ('certificates', 'Сертифікати'), ('contacts', 'Контакти'), ('offer', 'Оферта'), ('privacy', 'Політика'), ('catalog', 'Каталог'), ('search', 'Пошук'), ('cart', 'Кошик'), ('checkout', 'Оформлення'), ('thankyou', 'Дякуємо'), ('error', 'Помилки')], max_length=32, verbose_name='Сторінка')),
                ('key', models.CharField(max_length=64, verbose_name='Ключ')),
                ('label', models.CharField(blank=True, default='', max_length=128, verbose_name='Підпис у адмінці')),
                ('content_type', models.CharField(choices=[('text', 'Текст'), ('image', 'Фото'), ('url', 'Посилання'), ('video', 'Відео')], default='text', max_length=16, verbose_name='Тип')),
                ('text_html', models.TextField(blank=True, default='', verbose_name='Текст / HTML')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blocks/', verbose_name='Зображення')),
                ('link_url', models.CharField(blank=True, default='', max_length=512, verbose_name='URL посилання')),
                ('link_label', models.CharField(blank=True, default='', max_length=128, verbose_name='Текст посилання')),
                ('video_embed_url', models.URLField(blank=True, default='', verbose_name='Embed URL відео')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='blocks/video/', verbose_name='Файл відео')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Блок контенту',
                'verbose_name_plural': 'Блоки контенту',
                'ordering': ['page', 'sort_order', 'key'],
                'constraints': [models.UniqueConstraint(fields=('page', 'key'), name='unique_site_block_page_key')],
            },
        ),
    ]
