# Generated by Django 5.2.17 on 2026-09-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cms_siteblock_sitesettings_proxies'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogFiltersSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Каталог — фільтри',
                'verbose_name_plural': 'Каталог — фільтри',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='ProductPageSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Картка товару',
                'verbose_name_plural': 'Картка товару',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='SiteCartDrawerSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Шторка кошика',
                'verbose_name_plural': 'Шторка кошика',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.CreateModel(
            name='WishlistPageSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Обране',
                'verbose_name_plural': 'Обране',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.AlterField(
            model_name='siteblock',
            name='page',
            field=models.CharField(choices=[('home', 'Головна'), ('site', 'Сайт'), ('about', 'Про нас'), ('delivery', 'Доставка'), ('certificates', 'Сертифікати'), ('contacts', 'Контакти'), ('offer', 'Оферта'), ('privacy', 'Політика'), ('catalog', 'Каталог'), ('search', 'Пошук'), ('cart', 'Кошик'), ('checkout', 'Оформлення'), ('thankyou', 'Дякуємо'), ('error', 'Помилки'), ('wishlist', 'Обране'), ('product', 'Товар')], max_length=32, verbose_name='Сторінка'),
        ),
    ]
