# Generated by Django 5.2.17 on 2026-09-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_cms_phase2_shop_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroslide',
            name='alt_text_ru',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Alt (RU)'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='cta1_text_ru',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='Текст кнопки 1 (RU)'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='cta2_text_ru',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='Текст кнопки 2 (RU)'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='eyebrow_ru',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Надпис (RU)'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='lead_ru',
            field=models.TextField(blank=True, default='', verbose_name='Підпис (RU)'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='title_ru',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Заголовок (RU)'),
        ),
        migrations.AddField(
            model_name='highlightpoint',
            name='text_ru',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Текст (RU)'),
        ),
        migrations.AddField(
            model_name='highlightpoint',
            name='title_ru',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Заголовок (RU)'),
        ),
        migrations.AddField(
            model_name='review',
            name='city_ru',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Місто (RU)'),
        ),
        migrations.AddField(
            model_name='review',
            name='text_ru',
            field=models.TextField(blank=True, default='', verbose_name='Текст відгуку (RU)'),
        ),
        migrations.AddField(
            model_name='siteblock',
            name='link_label_ru',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Текст посилання (RU)'),
        ),
        migrations.AddField(
            model_name='siteblock',
            name='text_html_ru',
            field=models.TextField(blank=True, default='', verbose_name='Текст / HTML (RU)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_ru',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Адреса (RU)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_description_ru',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Meta description (RU)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='work_hours_ru',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Графік роботи (RU)'),
        ),
    ]
