# Generated by Django 5.2.17 on 2026-09-21 12:21

from django.db import migrations, models


def seed_pickup_points(apps, schema_editor):
    PickupPoint = apps.get_model("core", "PickupPoint")
    if PickupPoint.objects.exists():
        return
    address = "м. Київ, адреса уточнюється"
    address_ru = "г. Киев, адрес уточняется"
    for index in range(1, 5):
        PickupPoint.objects.create(
            title=f"Крамниця {index}",
            title_ru=f"Магазин {index}",
            address=address,
            address_ru=address_ru,
            order=index - 1,
            is_active=True,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_i18n_ru_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="PickupPoint",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=120, verbose_name="Назва крамниці")),
                ("title_ru", models.CharField(blank=True, default="", max_length=120, verbose_name="Назва (RU)")),
                ("address", models.CharField(max_length=255, verbose_name="Адреса")),
                ("address_ru", models.CharField(blank=True, default="", max_length=255, verbose_name="Адреса (RU)")),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Порожнє — телефон із налаштувань сайту.",
                        max_length=32,
                        verbose_name="Телефон",
                    ),
                ),
                (
                    "phone_raw",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Лише цифри та +. Порожнє — телефон сайту.",
                        max_length=32,
                        verbose_name="Телефон для tel:",
                    ),
                ),
                (
                    "hours",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Порожнє — графік із налаштувань сайту.",
                        max_length=120,
                        verbose_name="Графік",
                    ),
                ),
                ("hours_ru", models.CharField(blank=True, default="", max_length=120, verbose_name="Графік (RU)")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Порядок")),
                ("is_active", models.BooleanField(default=True, verbose_name="Активна")),
            ],
            options={
                "verbose_name": "Точка видачі",
                "verbose_name_plural": "Точки видачі",
                "ordering": ["order", "id"],
            },
        ),
        migrations.RunPython(seed_pickup_points, migrations.RunPython.noop),
    ]
