# Generated by Django 5.2.17 on 2026-09-22 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_pickuppoint_map_embed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlightpoint',
            name='icon',
            field=models.CharField(default='leaf', help_text='Оберіть іконку зі списку (листок, вантажівка, щит тощо).', max_length=30, verbose_name='Іконка'),
        ),
        migrations.AlterField(
            model_name='pickuppoint',
            name='map_embed',
            field=models.TextField(blank=True, default='', help_text='У Google Maps відкрийте крамницю → «Поділитися» → «Вбудувати карту» і вставте сюди скопійований код. Порожнє — покажеться карта-заглушка.', verbose_name='Карта Google'),
        ),
        migrations.AlterField(
            model_name='siteblock',
            name='text_html',
            field=models.TextField(blank=True, default='', verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='siteblock',
            name='text_html_ru',
            field=models.TextField(blank=True, default='', verbose_name='Текст (RU)'),
        ),
    ]
