# Generated by Django 5.2.17 on 2026-09-07 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_type', models.CharField(choices=[('phone_modal', 'Модальне вікно (телефон/знижка)'), ('buy_one_click', 'Купити в 1 клік'), ('contact_form', 'Форма на сторінці «Контакти»'), ('callback', 'Кнопка «Передзвоніть мені»'), ('newsletter', 'Підписка на email-розсилку')], default='phone_modal', max_length=32, verbose_name='Тип заявки')),
                ('name', models.CharField(blank=True, max_length=120, verbose_name="Ім'я")),
                ('phone', models.CharField(max_length=32, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('message', models.TextField(blank=True, verbose_name='Повідомлення')),
                ('source_page', models.CharField(blank=True, max_length=255, verbose_name='Сторінка джерела')),
                ('status', models.CharField(choices=[('new', 'Нова'), ('in_progress', 'В обробці'), ('done', 'Опрацьована')], default='new', max_length=16, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
    ]
