# Generated by Django 5.2.17 on 2026-09-29 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_softer_admin_help_texts'),
        ('leads', '0002_alter_lead_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='catalog.productvariant', verbose_name='Варіант'),
        ),
    ]
