# Generated by Django 5.2.17 on 2026-09-07 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва')),
                ('series', models.CharField(blank=True, max_length=120, verbose_name='Серія / продукт')),
                ('file', models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='Файл (PDF/зображення)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показувати на сайті')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Сертифікат',
                'verbose_name_plural': 'Сертифікати',
                'ordering': ['order', '-id'],
            },
        ),
    ]
