# Generated by Django 5.2.17 on 2026-09-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='series_ru',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Серія / продукт (RU)'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='title_ru',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Назва (RU)'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='file',
            field=models.FileField(blank=True, help_text='PDF лишається як є; зображення автоматично конвертуються в WebP.', null=True, upload_to='certificates/', verbose_name='Файл (PDF/зображення)'),
        ),
    ]
