# Generated by Django 5.2.17 on 2026-09-22 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_i18n_ru_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='file',
            field=models.FileField(blank=True, help_text='PDF або фото сертифіката. Звичайне зображення підійде — сайт збереже його сам.', null=True, upload_to='certificates/', verbose_name='Файл (PDF/зображення)'),
        ),
    ]
