"""CMS-секції фази 2: шторка кошика, фільтри, wishlist, PDP."""

from apps.core.site_content_registry_base import ContentSection, FieldGroup, _b

CONTENT_SECTIONS_SHOP: tuple[ContentSection, ...] = (
    ContentSection(
        slug="cart_drawer",
        page_slug="site",
        title="Шторка кошика",
        sidebar_icon="shopping_bag",
        preview_url="/",
        blocks=_b(
            "site",
            "cart_drawer_visible",
            "cart_drawer_title",
            "cart_drawer_empty",
            "cart_drawer_remove",
            "cart_drawer_total",
            "cart_drawer_view",
            "cart_drawer_checkout",
        ),
        field_groups=(
            FieldGroup("Видимість", ("cart_drawer_visible",)),
            FieldGroup(
                "Тексти",
                (
                    "cart_drawer_title",
                    "cart_drawer_empty",
                    "cart_drawer_remove",
                    "cart_drawer_total",
                    "cart_drawer_view",
                    "cart_drawer_checkout",
                ),
            ),
        ),
        admin_model_name="sitecartdrawersettings",
    ),
    ContentSection(
        slug="page",
        page_slug="wishlist",
        title="Обране",
        sidebar_icon="favorite",
        preview_url="/obrane/",
        visibility_key="page_section_visible",
        blocks=_b(
            "wishlist",
            "page_section_visible",
            "page_title",
            "loading",
            "empty_title",
            "empty_text",
            "empty_cta",
        ),
        field_groups=(
            FieldGroup("Видимість", ("page_section_visible",)),
            FieldGroup(
                "Тексти",
                ("page_title", "loading", "empty_title", "empty_text", "empty_cta"),
            ),
        ),
        admin_model_name="wishlistpagesettings",
    ),
    ContentSection(
        slug="page",
        page_slug="product",
        title="Картка товару",
        sidebar_icon="sell",
        preview_url="/katalog/",
        visibility_key="page_section_visible",
        blocks=_b(
            "product",
            "page_section_visible",
            "badge_hit",
            "badge_new",
            "badge_sale",
            "badge_own",
            "sku_label",
            "in_stock",
            "out_of_stock",
            "add_cart",
            "one_click",
            "wish_off",
            "wish_on",
            "desc_title",
            "related_title",
        ),
        field_groups=(
            FieldGroup("Видимість", ("page_section_visible",)),
            FieldGroup("Бейджі", ("badge_hit", "badge_new", "badge_sale", "badge_own")),
            FieldGroup(
                "Купівля",
                (
                    "sku_label",
                    "in_stock",
                    "out_of_stock",
                    "add_cart",
                    "one_click",
                    "wish_off",
                    "wish_on",
                ),
            ),
            FieldGroup("Блоки", ("desc_title", "related_title")),
        ),
        admin_model_name="productpagesettings",
    ),
)
