"""CMS-секції інфо / каталог / кошик / 404."""

from apps.core.site_content_registry_base import ContentSection, FieldGroup, _b

CONTENT_SECTIONS_PAGES: tuple[ContentSection, ...] = (
    ContentSection(
        slug="intro",
        page_slug="about",
        title="Про нас — Інтро",
        sidebar_icon="info",
        preview_url="/pro-nas/",
        visibility_key="intro_section_visible",
        blocks=_b("about", "intro_section_visible", "intro_title", "intro_lead", "intro_body"),
        field_groups=(
            FieldGroup("Видимість", ("intro_section_visible",)),
            FieldGroup("Контент", ("intro_title", "intro_lead", "intro_body")),
        ),
        admin_model_name="aboutintrosettings",
    ),
    ContentSection(
        slug="shelves",
        page_slug="about",
        title="Про нас — Полички",
        sidebar_icon="inventory_2",
        preview_url="/pro-nas/",
        visibility_key="shelves_section_visible",
        blocks=_b("about", "shelves_section_visible", "shelves_title", "shelves_list"),
        field_groups=(
            FieldGroup("Видимість", ("shelves_section_visible",)),
            FieldGroup("Контент", ("shelves_title", "shelves_list")),
        ),
        admin_model_name="aboutshelvessettings",
    ),
    ContentSection(
        slug="timeline",
        page_slug="about",
        title="Про нас — Хронологія",
        sidebar_icon="timeline",
        preview_url="/pro-nas/",
        visibility_key="timeline_section_visible",
        blocks=_b(
            "about",
            "timeline_section_visible",
            "timeline_1_year",
            "timeline_1_name",
            "timeline_1_text",
            "timeline_1_image",
            "timeline_2_year",
            "timeline_2_name",
            "timeline_2_text",
            "timeline_2_image",
            "timeline_3_year",
            "timeline_3_name",
            "timeline_3_text",
            "timeline_3_image",
            "timeline_4_year",
            "timeline_4_name",
            "timeline_4_text",
        ),
        field_groups=(
            FieldGroup("Видимість", ("timeline_section_visible",)),
            FieldGroup("2003", ("timeline_1_year", "timeline_1_name", "timeline_1_text", "timeline_1_image")),
            FieldGroup("2012", ("timeline_2_year", "timeline_2_name", "timeline_2_text", "timeline_2_image")),
            FieldGroup("2018", ("timeline_3_year", "timeline_3_name", "timeline_3_text", "timeline_3_image")),
            FieldGroup("2026", ("timeline_4_year", "timeline_4_name", "timeline_4_text")),
        ),
        admin_model_name="abouttimelinesettings",
    ),
    ContentSection(
        slug="philosophy",
        page_slug="about",
        title="Про нас — Філософія",
        sidebar_icon="spa",
        preview_url="/pro-nas/",
        visibility_key="philosophy_section_visible",
        blocks=_b(
            "about",
            "philosophy_section_visible",
            "philosophy_title",
            "philosophy_motto",
            "philosophy_text",
        ),
        field_groups=(
            FieldGroup("Видимість", ("philosophy_section_visible",)),
            FieldGroup("Контент", ("philosophy_title", "philosophy_motto", "philosophy_text")),
        ),
        admin_model_name="aboutphilosophysettings",
    ),
    ContentSection(
        slug="why",
        page_slug="about",
        title="Про нас — Чому ми",
        sidebar_icon="insights",
        preview_url="/pro-nas/",
        visibility_key="why_section_visible",
        blocks=_b(
            "about",
            "why_section_visible",
            "why_title",
            "why_1_value",
            "why_1_label",
            "why_2_value",
            "why_2_label",
            "why_3_value",
            "why_3_label",
            "why_4_value",
            "why_4_label",
        ),
        field_groups=(
            FieldGroup("Видимість", ("why_section_visible",)),
            FieldGroup("Заголовок", ("why_title",)),
            FieldGroup("Статистика", ("why_1_value", "why_1_label", "why_2_value", "why_2_label", "why_3_value", "why_3_label", "why_4_value", "why_4_label")),
        ),
        admin_model_name="aboutwhysettings",
    ),
    ContentSection(
        slug="produce",
        page_slug="about",
        title="Про нас — CTA",
        sidebar_icon="shopping_bag",
        preview_url="/pro-nas/",
        visibility_key="produce_section_visible",
        blocks=_b(
            "about",
            "produce_section_visible",
            "produce_title",
            "produce_image",
            "produce_btn_catalog",
            "produce_btn_call",
        ),
        field_groups=(
            FieldGroup("Видимість", ("produce_section_visible",)),
            FieldGroup("Фото", ("produce_image",)),
            FieldGroup("Контент", ("produce_title", "produce_btn_catalog", "produce_btn_call")),
        ),
        admin_model_name="aboutproducesettings",
    ),
    ContentSection(
        slug="page",
        page_slug="delivery",
        title="Доставка і оплата",
        sidebar_icon="local_shipping",
        preview_url="/dostavka-i-oplata/",
        visibility_key="page_section_visible",
        blocks=_b(
            "delivery",
            "page_section_visible",
            "page_title",
            "methods_title",
            "methods_html",
            "free_note",
            "payment_title",
            "payment_html",
            "faq_title",
            "faq_1_q",
            "faq_1_a",
            "faq_2_q",
            "faq_2_a",
            "faq_3_q",
            "faq_3_a",
        ),
        field_groups=(
            FieldGroup("Видимість", ("page_section_visible",)),
            FieldGroup("Доставка", ("page_title", "methods_title", "methods_html", "free_note")),
            FieldGroup("Оплата", ("payment_title", "payment_html")),
            FieldGroup("FAQ", ("faq_title", "faq_1_q", "faq_1_a", "faq_2_q", "faq_2_a", "faq_3_q", "faq_3_a")),
        ),
        admin_model_name="deliverypagesettings",
    ),
    ContentSection(
        slug="page",
        page_slug="certificates",
        title="Сертифікати — сторінка",
        sidebar_icon="workspace_premium",
        preview_url="/sertyfikaty/",
        visibility_key="page_section_visible",
        blocks=_b("certificates", "page_section_visible", "page_title", "page_lead", "empty_text"),
        field_groups=(
            FieldGroup("Видимість", ("page_section_visible",)),
            FieldGroup("Контент", ("page_title", "page_lead", "empty_text")),
        ),
        admin_model_name="certificatespagesettings",
    ),
    ContentSection(
        slug="page",
        page_slug="contacts",
        title="Контакти",
        sidebar_icon="location_on",
        preview_url="/kontakty/",
        visibility_key="page_section_visible",
        blocks=_b(
            "contacts",
            "page_section_visible",
            "page_title",
            "social_title",
            "stores_title",
            "label_phone",
            "label_hours",
            "label_address",
            "form_title",
            "form_cta",
        ),
        field_groups=(
            FieldGroup("Видимість", ("page_section_visible",)),
            FieldGroup(
                "Заголовки",
                ("page_title", "social_title", "stores_title", "label_phone", "label_hours", "label_address"),
                "Посилання Instagram, TikTok і Telegram задаються в налаштуваннях сайту.",
            ),
            FieldGroup("Форма", ("form_title", "form_cta")),
        ),
        admin_model_name="contactspagesettings",
        has_pickup_points=True,
    ),
    ContentSection(
        slug="page",
        page_slug="offer",
        title="Оферта",
        sidebar_icon="description",
        preview_url="/oferta/",
        visibility_key="page_section_visible",
        blocks=_b("offer", "page_section_visible", "page_title", "page_body"),
        field_groups=(
            FieldGroup("Видимість", ("page_section_visible",)),
            FieldGroup("Контент", ("page_title", "page_body")),
        ),
        admin_model_name="offerpagesettings",
    ),
    ContentSection(
        slug="page",
        page_slug="privacy",
        title="Політика",
        sidebar_icon="privacy_tip",
        preview_url="/privacy/",
        visibility_key="page_section_visible",
        blocks=_b("privacy", "page_section_visible", "page_title", "page_body"),
        field_groups=(
            FieldGroup("Видимість", ("page_section_visible",)),
            FieldGroup("Контент", ("page_title", "page_body")),
        ),
        admin_model_name="privacypagesettings",
    ),
    ContentSection(
        slug="page",
        page_slug="catalog",
        title="Каталог — сторінка",
        sidebar_icon="category",
        preview_url="/katalog/",
        visibility_key="page_section_visible",
        blocks=_b(
            "catalog",
            "page_section_visible",
            "page_title",
            "sale_title",
            "sale_crumb",
            "count_label",
            "filters_btn",
            "sort_popularity",
            "sort_price_asc",
            "sort_price_desc",
            "sort_new",
            "empty_title",
            "empty_text",
            "empty_cta",
        ),
        field_groups=(
            FieldGroup("Видимість", ("page_section_visible",)),
            FieldGroup("Заголовки", ("page_title", "sale_title", "sale_crumb", "count_label", "filters_btn")),
            FieldGroup(
                "Сортування",
                ("sort_popularity", "sort_price_asc", "sort_price_desc", "sort_new"),
            ),
            FieldGroup("Порожній стан", ("empty_title", "empty_text", "empty_cta")),
        ),
        admin_model_name="catalogpagesettings",
    ),
    ContentSection(
        slug="page",
        page_slug="search",
        title="Пошук",
        sidebar_icon="search",
        preview_url="/poshuk/",
        visibility_key="page_section_visible",
        blocks=_b(
            "search",
            "page_section_visible",
            "page_title",
            "hint_text",
            "empty_title",
            "empty_text",
            "empty_cta",
        ),
        field_groups=(
            FieldGroup("Видимість", ("page_section_visible",)),
            FieldGroup("Тексти", ("page_title", "hint_text", "empty_title", "empty_text", "empty_cta")),
        ),
        admin_model_name="searchpagesettings",
    ),
    ContentSection(
        slug="page",
        page_slug="cart",
        title="Кошик",
        sidebar_icon="shopping_cart",
        preview_url="/koshyk/",
        visibility_key="page_section_visible",
        blocks=_b("cart", "page_section_visible", "page_title", "empty_title", "empty_text", "empty_cta"),
        field_groups=(
            FieldGroup("Видимість", ("page_section_visible",)),
            FieldGroup("Тексти", ("page_title", "empty_title", "empty_text", "empty_cta")),
        ),
        admin_model_name="cartpagesettings",
    ),
    ContentSection(
        slug="page",
        page_slug="checkout",
        title="Оформлення",
        sidebar_icon="receipt_long",
        preview_url="/oformlennya/",
        visibility_key="page_section_visible",
        blocks=_b("checkout", "page_section_visible", "page_title"),
        field_groups=(
            FieldGroup("Видимість", ("page_section_visible",)),
            FieldGroup("Тексти", ("page_title",)),
        ),
        admin_model_name="checkoutpagesettings",
    ),
    ContentSection(
        slug="page",
        page_slug="thankyou",
        title="Дякуємо",
        sidebar_icon="celebration",
        preview_url="/oformlennya/dyakuyemo/",
        visibility_key="page_section_visible",
        blocks=_b("thankyou", "page_section_visible", "page_title", "page_lead"),
        field_groups=(
            FieldGroup("Видимість", ("page_section_visible",)),
            FieldGroup("Тексти", ("page_title", "page_lead")),
        ),
        admin_model_name="thankyoupagesettings",
    ),
    ContentSection(
        slug="page404",
        page_slug="error",
        title="Сторінка 404",
        sidebar_icon="error",
        preview_url="/storinka-yakoyi-nema/",
        visibility_key="page_404_visible",
        blocks=_b(
            "error",
            "page_404_visible",
            "page_404_title",
            "page_404_text",
            "page_404_cta_home",
            "page_404_cta_catalog",
        ),
        field_groups=(
            FieldGroup("Видимість", ("page_404_visible",)),
            FieldGroup(
                "Контент",
                ("page_404_title", "page_404_text", "page_404_cta_home", "page_404_cta_catalog"),
            ),
        ),
        admin_model_name="error404settings",
    ),
)
