"""CMS-секції головної та глобальних блоків."""

from apps.core.site_content_registry_base import ContentSection, FieldGroup, _b

CONTENT_SECTIONS_HOME: tuple[ContentSection, ...] = (

    ContentSection(
        slug="hero",
        page_slug="home",
        title="Головна — Hero",
        sidebar_title="Головна — Hero",
        sidebar_icon="image",
        preview_url="/",
        description="Слайди банера (фото + тексти). Статичні img/home/hero-*.jpg — fallback.",
        visibility_key="hero_section_visible",
        blocks=_b("home", "hero_section_visible"),
        field_groups=(FieldGroup("Видимість", ("hero_section_visible",)),),
        admin_model_name="homeherosettings",
        has_hero_slides=True,
    ),
    ContentSection(
        slug="trust",
        page_slug="home",
        title="Головна — Довіра",
        sidebar_icon="verified",
        preview_url="/",
        description="Пункти редагуються в «Переваги» (секція trust).",
        visibility_key="trust_section_visible",
        blocks=_b("home", "trust_section_visible"),
        field_groups=(FieldGroup("Видимість", ("trust_section_visible",)),),
        admin_model_name="hometrustsettings",
    ),
    ContentSection(
        slug="categories",
        page_slug="home",
        title="Головна — Категорії",
        sidebar_icon="grid_view",
        preview_url="/",
        visibility_key="categories_section_visible",
        blocks=_b(
            "home",
            "categories_section_visible",
            "categories_title",
            "categories_link_label",
            "categories_link",
        ),
        field_groups=(
            FieldGroup("Видимість", ("categories_section_visible",)),
            FieldGroup("Тексти", ("categories_title", "categories_link_label", "categories_link")),
        ),
        admin_model_name="homecategoriessettings",
    ),
    ContentSection(
        slug="hits",
        page_slug="home",
        title="Головна — Хіти",
        sidebar_icon="star",
        preview_url="/",
        visibility_key="hits_section_visible",
        blocks=_b("home", "hits_section_visible", "hits_title", "hits_link_label", "hits_link"),
        field_groups=(
            FieldGroup("Видимість", ("hits_section_visible",)),
            FieldGroup("Тексти", ("hits_title", "hits_link_label", "hits_link")),
        ),
        admin_model_name="homehitssettings",
    ),
    ContentSection(
        slug="news",
        page_slug="home",
        title="Головна — Новинки",
        sidebar_icon="new_releases",
        preview_url="/",
        visibility_key="news_section_visible",
        blocks=_b("home", "news_section_visible", "news_title"),
        field_groups=(
            FieldGroup("Видимість", ("news_section_visible",)),
            FieldGroup("Тексти", ("news_title",)),
        ),
        admin_model_name="homenewssettings",
    ),
    ContentSection(
        slug="story",
        page_slug="home",
        title="Головна — Історії",
        sidebar_icon="auto_stories",
        preview_url="/",
        visibility_key="story_section_visible",
        blocks=_b(
            "home",
            "story_section_visible",
            "story_title",
            "story_1_title",
            "story_1_text",
            "story_1_cta_label",
            "story_1_cta",
            "story_1_image",
            "story_2_title",
            "story_2_text",
            "story_2_cta_label",
            "story_2_cta",
            "story_2_image",
            "story_3_title",
            "story_3_text",
            "story_3_cta_label",
            "story_3_cta",
            "story_3_image",
        ),
        field_groups=(
            FieldGroup("Видимість", ("story_section_visible",)),
            FieldGroup("Секція", ("story_title",)),
            FieldGroup("Картка 1", ("story_1_title", "story_1_text", "story_1_cta_label", "story_1_cta", "story_1_image")),
            FieldGroup("Картка 2", ("story_2_title", "story_2_text", "story_2_cta_label", "story_2_cta", "story_2_image")),
            FieldGroup("Картка 3", ("story_3_title", "story_3_text", "story_3_cta_label", "story_3_cta", "story_3_image")),
        ),
        admin_model_name="homestorysettings",
    ),
    ContentSection(
        slug="benefits",
        page_slug="home",
        title="Головна — Переваги",
        sidebar_icon="loyalty",
        preview_url="/",
        description="Картки редагуються в «Переваги» (секція info).",
        visibility_key="benefits_section_visible",
        blocks=_b("home", "benefits_section_visible"),
        field_groups=(FieldGroup("Видимість", ("benefits_section_visible",)),),
        admin_model_name="homebenefitssettings",
    ),
    ContentSection(
        slug="sale",
        page_slug="home",
        title="Головна — Акції",
        sidebar_icon="sell",
        preview_url="/",
        visibility_key="sale_section_visible",
        blocks=_b("home", "sale_section_visible", "sale_title", "sale_link_label", "sale_link"),
        field_groups=(
            FieldGroup("Видимість", ("sale_section_visible",)),
            FieldGroup("Тексти", ("sale_title", "sale_link_label", "sale_link")),
        ),
        admin_model_name="homesalesettings",
    ),
    ContentSection(
        slug="reviews",
        page_slug="home",
        title="Головна — Відгуки",
        sidebar_icon="rate_review",
        preview_url="/",
        description="Список відгуків — у розділі «Відгуки».",
        visibility_key="reviews_section_visible",
        blocks=_b("home", "reviews_section_visible", "reviews_title"),
        field_groups=(
            FieldGroup("Видимість", ("reviews_section_visible",)),
            FieldGroup("Тексти", ("reviews_title",)),
        ),
        admin_model_name="homereviewssettings",
    ),
    ContentSection(
        slug="header",
        page_slug="site",
        title="Шапка",
        sidebar_icon="web",
        preview_url="/",
        description="Пункти меню та анонс — окрема видимість.",
        blocks=_b(
            "site",
            "header_announce_text",
            "header_announce_visible",
            "header_nav_home_visible",
            "header_nav_catalog_visible",
            "header_nav_about_visible",
            "header_nav_contacts_visible",
            "header_nav_sale_visible",
            "header_search_visible",
            "header_lang_visible",
            "header_wishlist_visible",
            "header_cart_visible",
            "header_nav_home_label",
            "header_nav_catalog_label",
            "header_nav_about_label",
            "header_nav_contacts_label",
            "header_nav_sale_label",
            "header_search_placeholder",
        ),
        field_groups=(
            FieldGroup("Анонс", ("header_announce_visible", "header_announce_text")),
            FieldGroup(
                "Навігація",
                (
                    "header_nav_home_visible",
                    "header_nav_home_label",
                    "header_nav_catalog_visible",
                    "header_nav_catalog_label",
                    "header_nav_about_visible",
                    "header_nav_about_label",
                    "header_nav_contacts_visible",
                    "header_nav_contacts_label",
                    "header_nav_sale_visible",
                    "header_nav_sale_label",
                ),
            ),
            FieldGroup(
                "Дії",
                (
                    "header_search_visible",
                    "header_search_placeholder",
                    "header_lang_visible",
                    "header_wishlist_visible",
                    "header_cart_visible",
                ),
            ),
        ),
        admin_model_name="siteheadersettings",
    ),
    ContentSection(
        slug="footer",
        page_slug="site",
        title="Підвал",
        sidebar_icon="vertical_align_bottom",
        preview_url="/#footer",
        blocks=_b(
            "site",
            "footer_cta_visible",
            "footer_cta_title",
            "footer_cta_text",
            "footer_cta_btn",
            "footer_col_cats_title",
            "footer_col_info_title",
            "footer_col_contacts_title",
            "footer_link_about_visible",
            "footer_link_delivery_visible",
            "footer_link_offer_visible",
            "footer_copyright",
        ),
        field_groups=(
            FieldGroup(
                "Newsletter",
                ("footer_cta_visible", "footer_cta_title", "footer_cta_text", "footer_cta_btn"),
            ),
            FieldGroup(
                "Колонки",
                (
                    "footer_col_cats_title",
                    "footer_col_info_title",
                    "footer_col_contacts_title",
                    "footer_link_about_visible",
                    "footer_link_delivery_visible",
                    "footer_link_offer_visible",
                ),
            ),
            FieldGroup("Низ", ("footer_copyright",)),
        ),
        admin_model_name="sitefootersettings",
    ),
    ContentSection(
        slug="lead_modal",
        page_slug="site",
        title="Модалка заявки",
        sidebar_icon="campaign",
        preview_url="/",
        blocks=_b(
            "site",
            "lead_modal_visible",
            "lead_modal_title",
            "lead_modal_lead",
            "lead_modal_cta",
            "lead_modal_agree",
            "lead_modal_success_title",
            "lead_modal_success_text",
        ),
        field_groups=(
            FieldGroup("Видимість", ("lead_modal_visible",)),
            FieldGroup(
                "Форма",
                ("lead_modal_title", "lead_modal_lead", "lead_modal_cta", "lead_modal_agree"),
            ),
            FieldGroup("Успіх", ("lead_modal_success_title", "lead_modal_success_text")),
        ),
        admin_model_name="siteleadmodalsettings",
    ),
    ContentSection(
        slug="fab",
        page_slug="site",
        title="Кнопка звʼязку",
        sidebar_icon="call",
        preview_url="/",
        blocks=_b("site", "fab_visible"),
        field_groups=(FieldGroup("Видимість", ("fab_visible",)),),
        admin_model_name="sitefabsettings",
    ),
)
