# Generated by Django 5.2.17 on 2026-09-07 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Назва на сайті')),
                ('erp_name', models.CharField(blank=True, help_text='Заповнюється, якщо назва на сайті відрізняється від довідника.', max_length=160, verbose_name='Назва в обліковій системі')),
                ('slug', models.SlugField(max_length=180, unique=True, verbose_name='URL-адреса (slug)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Зображення')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортування')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.category', verbose_name='Батьківська категорія')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=64, unique=True, verbose_name='Код товару (SKU)')),
                ('name', models.CharField(max_length=255, verbose_name='Назва на сайті')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL-адреса (slug)')),
                ('short_description', models.CharField(blank=True, max_length=255, verbose_name='Короткий опис')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('characteristics', models.JSONField(blank=True, default=dict, verbose_name='Характеристики')),
                ('brand', models.CharField(blank=True, max_length=120, verbose_name='Бренд / виробник')),
                ('country_of_origin', models.CharField(blank=True, max_length=120, verbose_name='Країна виробник')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Базова ціна')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стара ціна (для акції)')),
                ('is_own_production', models.BooleanField(default=False, verbose_name='Власне виробництво')),
                ('is_hit', models.BooleanField(default=False, verbose_name='Хіт продажу')),
                ('is_new', models.BooleanField(default=False, verbose_name='Новинка')),
                ('is_sale', models.BooleanField(default=False, verbose_name='Акція / знижка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний (видимий на сайті)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Зображення')),
                ('alt', models.CharField(blank=True, max_length=255, verbose_name='Alt-текст')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Фото товару',
                'verbose_name_plural': 'Фото товару',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80, verbose_name='Назва варіанту (напр. «500 мл»)')),
                ('sku_variant', models.CharField(blank=True, max_length=64, verbose_name='Код варіанту')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стара ціна')),
                ('stock_qty', models.PositiveIntegerField(default=0, verbose_name='Залишок')),
                ('is_default', models.BooleanField(default=False, verbose_name='Варіант за замовчуванням')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Варіант товару',
                'verbose_name_plural': 'Варіанти товару',
                'ordering': ['order', 'id'],
            },
        ),
    ]
