# Generated by Django 5.2.17 on 2026-09-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, help_text='Залиште порожнім — згенерується автоматично з назви (кирилиця транслітерується).', max_length=180, unique=True, verbose_name='URL-адреса (slug)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, help_text='Залиште порожнім — згенерується автоматично з назви (кирилиця транслітерується).', max_length=255, unique=True, verbose_name='URL-адреса (slug)'),
        ),
    ]
