# Generated by Django 5.2.17 on 2026-09-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_slug_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Для підкатегорій (рівні 2–3). Якщо порожньо — показується іконка-соняшник за замовчуванням.', null=True, upload_to='categories/', verbose_name='Іконка категорії'),
        ),
    ]
