# Generated by Django 5.2.17 on 2026-09-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_category_image_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pack_volume',
            field=models.CharField(blank=True, help_text='Наприклад: 6 мл, 100 мл, 1 л, 500 г. Окремі фасування — окремі товари.', max_length=80, verbose_name='Обʼєм / фасування'),
        ),
    ]
