# Generated by Django 5.2.17 on 2026-09-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_pack_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='PNG або WebP. Для кореневих — шапка/головна; для підкатегорій — плитки в каталозі. Якщо порожньо — статична іконка (корені) або соняшник за замовчуванням (підкатегорії).', null=True, upload_to='categories/', verbose_name='Іконка категорії'),
        ),
    ]
