# Generated by Django 5.2.17 on 2026-09-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_rename_category_level_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_ru',
            field=models.TextField(blank=True, default='', verbose_name='Опис (RU)'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(blank=True, default='', max_length=160, verbose_name='Назва на сайті (RU)'),
        ),
        migrations.AddField(
            model_name='product',
            name='characteristics_ru',
            field=models.JSONField(blank=True, default=dict, help_text='Російські підписи характеристик (ті самі ключі або повний словник).', verbose_name='Характеристики (RU)'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=models.TextField(blank=True, default='', verbose_name='Опис (RU)'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Назва на сайті (RU)'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_ru',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Короткий опис (RU)'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='alt_ru',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Alt-текст (RU)'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='label_ru',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Назва варіанту (RU)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='PNG/JPG/WebP — автоматично збережеться як WebP. Головні: якщо порожньо — іконка шапки/головної. 2–3 рівень: якщо порожньо — соняшник.', null=True, upload_to='categories/', verbose_name='Іконка категорії'),
        ),
    ]
