# Generated by Django 5.2.17 on 2026-09-17 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_i18n_ru_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_type', models.CharField(choices=[('brand', 'Бренд'), ('country', 'Країна'), ('volume', 'Обʼєм / вага'), ('power', 'Потужність')], db_index=True, max_length=20, verbose_name='Тип фільтра')),
                ('value', models.CharField(max_length=120, verbose_name='Значення')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активне')),
            ],
            options={
                'verbose_name': 'Значення фільтра',
                'verbose_name_plural': 'Значення фільтрів',
                'ordering': ['filter_type', 'order', 'value'],
                'constraints': [models.UniqueConstraint(fields=('filter_type', 'value'), name='catalog_filteroption_type_value_uniq')],
            },
        ),
        migrations.CreateModel(
            name='BrandFilterOption',
            fields=[
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренди',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.filteroption',),
        ),
        migrations.CreateModel(
            name='CountryFilterOption',
            fields=[
            ],
            options={
                'verbose_name': 'Країна',
                'verbose_name_plural': 'Країни',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.filteroption',),
        ),
        migrations.CreateModel(
            name='PowerFilterOption',
            fields=[
            ],
            options={
                'verbose_name': 'Потужність',
                'verbose_name_plural': 'Потужність',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.filteroption',),
        ),
        migrations.CreateModel(
            name='VolumeFilterOption',
            fields=[
            ],
            options={
                'verbose_name': 'Обʼєм / вага',
                'verbose_name_plural': 'Обʼєм / вага',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.filteroption',),
        ),
        migrations.CreateModel(
            name='CategoryFilterSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_type', models.CharField(choices=[('brand', 'Бренд'), ('country', 'Країна'), ('volume', 'Обʼєм / вага'), ('power', 'Потужність')], db_index=True, max_length=20, verbose_name='Тип фільтра')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Увімкнено')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filter_settings', to='catalog.category', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Привʼязка фільтра до категорії',
                'verbose_name_plural': 'Привʼязки фільтрів до категорій',
                'ordering': ['category__order', 'category__name', 'filter_type'],
                'constraints': [models.UniqueConstraint(fields=('category', 'filter_type'), name='catalog_catfilter_cat_type_uniq')],
            },
        ),
    ]
