# Generated by Django 5.2.17 on 2026-09-17 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0012_seed_filter_dictionary"),
    ]

    operations = [
        migrations.CreateModel(
            name="CatalogFilter",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120, verbose_name="Назва")),
                ("name_ru", models.CharField(blank=True, default="", max_length=120, verbose_name="Назва (RU)")),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Параметр у URL (?brand=…). Залиште порожнім — згенерується з назви.",
                        max_length=64,
                        unique=True,
                        verbose_name="Ключ (slug)",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Порядок")),
                ("is_active", models.BooleanField(default=True, verbose_name="Активний")),
                (
                    "use_country_labels",
                    models.BooleanField(
                        default=False,
                        help_text="Для фільтра країни — підставляти локалізовані назви.",
                        verbose_name="Показувати як назви країн",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фільтр",
                "verbose_name_plural": "Фільтри",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="CatalogFilterCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_enabled", models.BooleanField(default=True, verbose_name="Увімкнено")),
                (
                    "catalog_filter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_bindings",
                        to="catalog.catalogfilter",
                        verbose_name="Фільтр",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="catalog_filter_bindings",
                        to="catalog.category",
                        verbose_name="Категорія",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привʼязка до категорії",
                "verbose_name_plural": "Привʼязки до категорій",
                "ordering": ["category__order", "category__name"],
            },
        ),
        migrations.CreateModel(
            name="CatalogFilterValue",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value", models.CharField(max_length=120, verbose_name="Значення")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Порядок")),
                ("is_active", models.BooleanField(default=True, verbose_name="Активне")),
                (
                    "catalog_filter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="catalog.catalogfilter",
                        verbose_name="Фільтр",
                    ),
                ),
            ],
            options={
                "verbose_name": "Значення фільтра",
                "verbose_name_plural": "Значення фільтра",
                "ordering": ["order", "value"],
            },
        ),
        migrations.CreateModel(
            name="ProductAttribute",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value", models.CharField(max_length=120, verbose_name="Значення")),
                (
                    "catalog_filter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_attrs",
                        to="catalog.catalogfilter",
                        verbose_name="Фільтр",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filter_attrs",
                        to="catalog.product",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Атрибут товару",
                "verbose_name_plural": "Атрибути товарів",
            },
        ),
        migrations.AddConstraint(
            model_name="catalogfiltercategory",
            constraint=models.UniqueConstraint(
                fields=("catalog_filter", "category"),
                name="catalog_filtercat_filter_cat_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="catalogfiltervalue",
            constraint=models.UniqueConstraint(
                fields=("catalog_filter", "value"),
                name="catalog_filtervalue_filter_value_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="productattribute",
            constraint=models.UniqueConstraint(
                fields=("product", "catalog_filter"),
                name="catalog_productattr_product_filter_uniq",
            ),
        ),
    ]
