# Generated by Django 5.2.17 on 2026-09-22 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_split_pack_filters_remove_power'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Завантажте іконку або залиште порожньою. Головні розділи — тоді буде стандартна іконка сайту; підрозділи — соняшник.', null=True, upload_to='categories/', verbose_name='Іконка категорії'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, help_text='Краще не змінювати — заповниться само з назви.', max_length=180, unique=True, verbose_name='Адреса в посиланні'),
        ),
        migrations.AlterField(
            model_name='product',
            name='characteristics',
            field=models.JSONField(blank=True, default=dict, help_text='Рядки «назва → значення», наприклад «Обʼєм → 100 мл».', verbose_name='Характеристики'),
        ),
        migrations.AlterField(
            model_name='product',
            name='characteristics_ru',
            field=models.JSONField(blank=True, default=dict, help_text='Ті самі характеристики російською, рядки «назва → значення».', verbose_name='Характеристики (RU)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Повний опис товару. Пишіть звичайними реченнями — Enter робить новий абзац. Жирний, списки й посилання — кнопками зверху.', verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pack_volume',
            field=models.CharField(blank=True, help_text='Обʼєм, вага або кількість: 6 мл, 100 мл, 1 л, 10 г, 500 г, 5 кг, 10 шт. Окремі варіанти краще робити варіантами товару.', max_length=80, verbose_name='Обʼєм / вага / кількість'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, help_text='Краще не змінювати — заповниться само з назви.', max_length=255, unique=True, verbose_name='Адреса в посиланні'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='label',
            field=models.CharField(help_text='Наприклад: «100 мл», «1 л», «10 г», «500 г», «10 шт» — не розміри одягу S/M/L.', max_length=80, verbose_name='Назва варіанту'),
        ),
    ]
