# Generated by Django 5.2.17 on 2026-09-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_softer_admin_help_texts'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='max_per_order',
            field=models.PositiveIntegerField(blank=True, help_text='Порожньо — без ліміту («в одні руки»).', null=True, verbose_name='Макс. шт. в одному замовленні'),
        ),
    ]
